import type { TabelaDePadroes } from '../defaults'

/**
 * Engine defaults of table "0.15.1", as `createDefaultNode` returned them when it was written
 * (values in the scene's JSON encoding). FROZEN: scenes stamped with this id are expanded with
 * exactly these values. If the engine's defaults change, add a new table; never edit this one.
 */
export const PADROES_0_15_1: TabelaDePadroes = {
  "id": "0.15.1",
  "campos": {
    "parentId": null,
    "childIds": [],
    "x": 0,
    "y": 0,
    "width": 100,
    "height": 100,
    "rotation": 0,
    "source": {
      "format": null,
      "id": null,
      "orderKey": null,
      "editedFields": [],
      "fig": {
        "rawSize": null,
        "rawTransform": null,
        "rawNodeFields": {},
        "layout": null,
        "symbolOverrides": [],
        "componentPropAssignments": [],
        "derivedSymbolData": [],
        "derivedSymbolDataLayoutVersion": null,
        "uniformScaleFactor": null
      }
    },
    "derivedLayout": null,
    "fills": [],
    "strokes": [],
    "effects": [],
    "layoutGrids": [],
    "guides": [],
    "fillStyleId": null,
    "strokeStyleId": null,
    "textStyleId": null,
    "effectStyleId": null,
    "gridStyleId": null,
    "sharedStyleType": null,
    "opacity": 1,
    "cornerRadius": 0,
    "topLeftRadius": 0,
    "topRightRadius": 0,
    "bottomRightRadius": 0,
    "bottomLeftRadius": 0,
    "independentCorners": false,
    "cornerSmoothing": 0,
    "visible": true,
    "locked": false,
    "clipsContent": false,
    "text": "",
    "fontSize": 14,
    "fontFamily": "Inter",
    "fontWeight": 400,
    "italic": false,
    "textAlignHorizontal": "LEFT",
    "textDirection": "AUTO",
    "textLanguage": null,
    "leadingTrim": "NONE",
    "lineHeight": null,
    "letterSpacing": 0,
    "layoutMode": "NONE",
    "layoutDirection": "AUTO",
    "layoutWrap": "NO_WRAP",
    "primaryAxisAlign": "MIN",
    "counterAxisAlign": "MIN",
    "primaryAxisSizing": "FIXED",
    "counterAxisSizing": "FIXED",
    "itemSpacing": 0,
    "counterAxisSpacing": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "blendMode": "PASS_THROUGH",
    "layoutPositioning": "AUTO",
    "layoutGrow": 0,
    "layoutAlignSelf": "AUTO",
    "vectorNetwork": null,
    "handleMirroring": "NONE",
    "fillGeometry": [],
    "strokeGeometry": [],
    "arcData": null,
    "textAlignVertical": "TOP",
    "textAutoResize": "NONE",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "textDecorationStyle": "SOLID",
    "textDecorationThickness": null,
    "textDecorationFills": [],
    "textDecorationSkipInk": true,
    "textUnderlineOffset": null,
    "maxLines": null,
    "styleRuns": [],
    "fontVariations": [],
    "fontFeatures": [],
    "horizontalConstraint": "MIN",
    "verticalConstraint": "MIN",
    "strokeCap": "NONE",
    "strokeJoin": "MITER",
    "dashPattern": [],
    "borderTopWeight": 0,
    "borderRightWeight": 0,
    "borderBottomWeight": 0,
    "borderLeftWeight": 0,
    "independentStrokeWeights": false,
    "strokeMiterLimit": 4,
    "minWidth": null,
    "maxWidth": null,
    "minHeight": null,
    "maxHeight": null,
    "isMask": false,
    "maskType": "ALPHA",
    "maskIsOutline": false,
    "gridTemplateColumns": [],
    "gridTemplateRows": [],
    "gridColumnGap": 0,
    "gridRowGap": 0,
    "gridPosition": null,
    "counterAxisAlignContent": "AUTO",
    "itemReverseZIndex": false,
    "strokesIncludedInLayout": false,
    "expanded": true,
    "textTruncation": "DISABLED",
    "autoRename": true,
    "pointCount": 5,
    "starInnerRadius": 0.38,
    "componentId": null,
    "instanceOverrides": {
      "self": {
        "$cena": "map",
        "v": []
      },
      "descendants": {
        "$cena": "map",
        "v": []
      }
    },
    "componentPropertyDefinitions": [],
    "componentPropertyReferences": [],
    "componentPropertyAssignments": {},
    "componentPropertyValues": {},
    "componentKey": null,
    "sourceLibraryKey": null,
    "publishId": null,
    "overrideKey": null,
    "sharedSymbolVersion": null,
    "publishedVersion": null,
    "librarySource": null,
    "isPublishable": false,
    "isSymbolPublishable": false,
    "symbolDescription": "",
    "symbolLinks": [],
    "variantPropSpecs": [],
    "boundVariables": {},
    "variableModes": {},
    "exportSettings": [],
    "pluginData": [],
    "pluginRelaunchData": [],
    "internalOnly": false,
    "flipX": false,
    "flipY": false,
    "textPicture": null,
    "derivedTextGlyphs": null,
    "textPathData": null,
    "textPathBox": null
  },
  "porTipo": {
    "TEXT": {
      "fills": [
        {
          "type": "SOLID",
          "color": {
            "r": 0,
            "g": 0,
            "b": 0,
            "a": 1
          },
          "opacity": 1,
          "visible": true
        }
      ]
    }
  }
}
